version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: scriptedrealms-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
